### PR TITLE
Panel: Make dismissible option work on-the-fly

### LINKED ISSUE #7884: Panel: Implement on-the-fly support for option "dismissible"
We need a solution that does not involve unconditionally creating the modal (as in https://github.com/jquery/jquery-mobile/pull/7537).

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-7884

### CODE REVIEW

**Comment by arschmitz** [comment]
@gabrielschulhof Im a little hesitant to make this work on one option with out making it work on the rest of the options.

**Comment by gabrielschulhof** [comment]
@arschmitz well, yeah. I guess we can review panel and make all options work.

**Comment by arschmitz** [comment]
@gabrielschulhof see how much work it looks like we already started prototyping the rewrite so dont want to invest much

**Comment by arschmitz** [comment]
@gabrielschulhof if we are going to do this should do it as part of classes and close this maybe?

**Comment by arschmitz** [comment]
im going to close this since its super old we should do all options together

**Pull request closed without merging**
