### PR TITLE
Init: Add classes ui-noboxshadow and ui-nosvg

### LINKED ISSUE #6168: Move adding of no-support classes from support.js to init.js
Currently support.js contains scripts that add the ```ui-nosvg``` and ```ui-noboxshadow``` classes. Both should be moved to init.js. For no-svg this means we first have to make the test extend ```$.support```.

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Init: Move addition of ui-noboxshadow class from support
Init: Support no longer adds ui-nosvg class, so init does it

Fixes gh-6168

### CODE REVIEW

**Comment by arschmitz** [comment]
@gabrielschulhof what exactly is the reason for this the issue gives no reason why these should be moved or problem it solves?

**Comment by gabrielschulhof** [comment]
@arschmitz The reason is, presumably, that the support module should make no DOM modifications, but it should only test. It is up to the rest of the library to decide what to do with the results of the support tests.

@jaspermdegroot when you opened #6168 that's what you were thinking about, right?

**Comment by jaspermdegroot** [comment]
@gabrielschulhof 

Yes, that's correct. I should have added the reason to that ticket.

**Comment by arschmitz** [comment]
@gabrielschulhof @jaspermdegroot Can you give me a little more on why you think it should be this way? To me these are all support tests. Some are a different style of support test. They are modernizer style tests, where classes are added, to indicate support for a particular feature.

**Comment by gabrielschulhof** [comment]
Well, for one, there's that Series 40 issue (https://github.com/jquery/jquery-mobile/issues/5309) where making any DOM mods will cause a crash ...

**Comment by arschmitz** [comment]
@gabrielschulhof how would this fix that? Thats not caused by changing classes its caused but by certain types actual DOM manipulation. If you look at our support tests https://github.com/jquery/jquery-mobile/blob/master/js/support.js you will see a good chunk of them do some sort of DOM manipulation as part of the actual test.

**Comment by gabrielschulhof** [comment]
Back to you, @jaspermdegroot :)

**Comment by gabrielschulhof** [comment]
Wait ... there is one point to be made here ... we do add that fake body tag for a bunch of the tests, but we remove it afterwards. The addition of these classes is a permanent modification of the DOM. Maybe that was undesired in situations where the support tests alone are being used. Nevertheless, if @jaspermdegroot can expound on this subject, I welcome his comment(s).

**Comment by jaspermdegroot** [comment]
I looked up the IRC log from the day that I opened that ticket.
Looks like it had to do with failing tests. See http://irc.jquery.org/%23jqueryui-dev/default_%23jqueryui-dev_20130715.log.html#t13:16:54 and http://irc.jquery.org/%23jqueryui-dev/default_%23jqueryui-dev_20130715.log.html#t14:43:46

**Comment by arschmitz** [comment]
I don't really see the point in this still unless someone feels strongly about this and has some good reason id like to just close this? @gabrielschulhof @jaspermdegroot @cgack ?

**Comment by jaspermdegroot** [comment]
When @gabrielschulhof mentioned that the support module shouldn't make DOM manipulations I thought that this was the reason, but now I think of it that doesn't make sense. Reason for the ticket was a failing test according to the IRC discussion so if they no longer fail we can close.

**Pull request closed without merging**
