### PR TITLE
Flipswitch: Fixes #8071

### LINKED ISSUE #8071: flipswitch destroy throws exception
Calling method destroy (https://api.jquerymobile.com/flipswitch/#method-destroy) on a flipswitch control throws an exception:

Object doesn't support property or method 'removeClass'
http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.js line 9408: this.removeClass( "ui-flipswitch-input" );

### PR DESCRIPTION
**Pull request by kapilgarg1996**
Fixes #8071

### CODE REVIEW

**Comment by arschmitz** [comment]
Can you add a test for this please

**Comment by kapilgarg1996** [comment]
Okay :+1:

**Comment by kapilgarg1996** [comment]
@arschmitz tests added.

**Comment by arschmitz** [comment]
@kapilgarg1996 this should not use `throws` it should just test the destroy method using `domEqual` if it throws an error the test will fail

**Pull request closed without merging**
