### PR TITLE
demos: Fixes-8117 point to cdn versions

### LINKED ISSUE #8117: Demos: pages-multi-page and pages-single-page wrongly refer to CDN versions
Text in the pages-multi-page and pages-single-page demos say "All the CSS and JS is linked to the jQuery CDN versions" but instead they link to relative URIs:
``` HTML
<link rel="stylesheet" href="../../css/themes/default/jquery.mobile.css">
<link rel="stylesheet" href="../_assets/css/jqm-demos.css">
<link rel="shortcut icon" href="../favicon.ico">
<script src="../../external/jquery/jquery.js"></script>
```
https://github.com/jquery/jquery-mobile/blob/master/demos/pages-multi-page/index.html
https://github.com/jquery/jquery-mobile/blob/master/demos/pages-single-page/index.html

### PR DESCRIPTION
**Pull request by kapilgarg1996**
Fixes #8117

### CODE REVIEW

**Comment by arschmitz** [comment]
Thank you for working on this however we never point to fixed versions in demos like this. the links were correct just the wording needed to be changed.

**Comment by kapilgarg1996** [comment]
Actually the main page http://demos.jquerymobile.com/1.4.5/pages/ consists both the single page and multipage templates.
So should we instruct the user on the template pages to use the template code present on the main page ?

**Comment by arschmitz** [comment]
@kapilgarg1996 i'm not sure what you mean. I believe the only change we need to make here is on http://demos.jquerymobile.com/1.4.5/pages-single-page/ and http://demos.jquerymobile.com/1.4.5/pages-multi-page/ to remove the sentence "All the CSS and JS is linked to the jQuery CDN versions so this is super easy to set up." 

The only alternative i can see would be to change this in the demos to point at the git build and in the demos build add a step to change these to point at the current cdn version. @gabrielschulhof @jaspermdegroot thoughts?

**Comment by kapilgarg1996** [comment]
@arschmitz 
I mean that this page http://demos.jquerymobile.com/1.4.5/pages/ actually contains the single page and multipage template code. So we can add this line..
"http://demos.jquerymobile.com/1.4.5/pages/ contains the template code. Just copy the code from there."

**Comment by arschmitz** [comment]
@kapilgarg1996 right i think what your not understanding though is I dont  think we want that line there. It would not be correct, and would have to be updated on every release and still would need to point at a git build in the repo.

**Comment by kapilgarg1996** [comment]
@arschmitz oh yeah right..

**Comment by arschmitz** [comment]
@kapilgarg1996 I'm going to close this since as we discussed its not the fix we need. Feel free to open a new pull request with the proper change though.

**Pull request closed without merging**
