### PR TITLE
Build: Bump phantomjs version through grunt-contrib-qunit

### PR DESCRIPTION
**Pull request by apsdehal**

### CODE REVIEW

**Comment by arschmitz** [comment]
Do you think we could keep coverage and just remove coveralls reporting?

**Comment by apsdehal** [comment]
Is there any other alternative for coverage, ui uses grunt-contrib-qunit and I would like to stick it, instead of some fork.

**Comment by arschmitz** [comment]
i like blanket.js use it on a few projects

**Comment by apsdehal** [comment]
Ok, I will include it in a separate PR.

**Comment by apsdehal** [comment]
@arschmitz Should I merge this one?

**Comment by arschmitz** [comment]
👍

**Pull request closed without merging**
