### PR TITLE
Demos: Fixed last row styling for lower resolutions

### LINKED ISSUE #7954: Demos: Reflow table, last entry without stripes
Hi

If both styles, .table-strike and .table-stroke are given to a reflow table, 
the last row will have no stripes in the reflow mode.

You could reproduce this issue in your demo if you scale down the width of the window to reflow the table to the smartphone view:
http://demos.jquerymobile.com/1.4.5/table-reflow-stripes-strokes/

### PR DESCRIPTION
**Pull request by kakul**
Fixes gh-7954

### CODE REVIEW

**Comment by arschmitz** [comment]
@jaspermdegroot want to take a look at this?

**Comment by jaspermdegroot** [comment]
@arschmitz - Sure, will do.

**Comment by jaspermdegroot** [comment]
@kakul 

Thanks for the PR.

The idea was to give the last row a bit darker border bottom. Instead of removing those styles for the last row we could wrap them in a media query to make them only apply on wider screens, but I think it looks good enough without them so I am fine with removing it.

On small screens the last table row looks still a bit different than the others. This can be fixed by removing the  ```.movie-list tbody tr:last-child``` selector from the first rule. Can you make that change?

**Comment by kakul** [comment]
Hello @jaspermdegroot
Thanks for your review. I have made the change as you proposed.

**Comment by jaspermdegroot** [comment]
@kakul - Thanks!

@arschmitz - This can be merged in master.

**Comment by arschmitz** [comment]
@jaspermdegroot thank you
@kakul will merge this shortly

**Pull request closed without merging**
