### PR TITLE
All: Make sure events are well-formed and offsets are valid

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-8134

### CODE REVIEW

**Comment by arschmitz** [comment]
Changes to offset should not be included here these are not final yet and are likely to be reverted.

**Comment by arschmitz** [comment]
Other then removing the offset changes this looks good

**Comment by gabrielschulhof** [comment]
@arschmitz I've removed the offset stuff. It's all event-related now.

**Comment by arschmitz** [comment]
This has TONS of failures on git still not sure if these are related or not have not looked yet. some are offset those can be ignored.

**Comment by gabrielschulhof** [comment]
@arschmitz there's been some new breakage in core related to some variable named ```url``` being not a string and core unconditionally calling ```.indexOf()``` on it.

**Comment by arschmitz** [comment]
ok lets go ahead and get this landed :+1:

**Pull request closed without merging**
