### PR TITLE
Fix to text about datepicker.

### PR DESCRIPTION
**Pull request by s-moon**
Paragraph (originally) was difficult to understand. Hopefully this makes a little more sense!

### CODE REVIEW

**Comment by s-moon** [comment]
Hi,

I did sign the CLA but despite that, got the error label. I then re-signed (just in case). If there is anything I can do, please let me know.

Thanks,

**Comment by agcolom** [comment]
@s-moon Hi, I've just checked your signature and it all looks fine to me (both your name and email address seem to match those recorded on the PR). 
@scottgonzalez Are you aware of any issues with the CLA tracker at present? Thanks.

**Comment by agcolom** [comment]
@s-moon Thanks for the PR. It looks good and can be merged as soon as we figure out why we're getting this error on the CLA check :-)

**Comment by scottgonzalez** [comment]
I don't know why the CLA check is failing. I do know why the CLA results page doesn't show any information though. See https://github.com/jquery/jquery-wp-content/issues/390.

**Comment by s-moon** [comment]
Any update on whether the CLA is fixable?

Thanks,

**Comment by arschmitz** [comment]
landed in 1.5-dev closing

**Pull request closed without merging**
