### PR TITLE
Forms: fixes regression bug from ui-mini fix.

### LINKED ISSUE #7821: Mini slider is broken in 1.4.5
Test case: http://jsbin.com/zuyapirepi/1/edit
Workaround: .ui-slider-track.ui-mini { margin: 0 15px 0 68px; }

Originally reported here: https://plus.google.com/105587967205913541400/posts/4DQVj3o5xYE
It's also broken on official demo page: http://demos.jquerymobile.com/1.4.5/slider/

### PR DESCRIPTION
**Pull request by ldeluca**
fixed issue where slider was no longer over input field.

Fixes #7821

### CODE REVIEW

**Comment by arschmitz** [comment]
@ldeluca Bump!

**Comment by ldeluca** [comment]
@arschmitz I have my local environment building the docs now and for the life of me I don't see the issue.  The code version i'm on has my changes but viewing the range slider page looks okay to me.  Am I doing something wrong maybe with how I build?  I'm viewing on Chrome.  The css change should only effect .ui-mini classes so I'm also confused why it'd break all of the rangesliders.  

my change: .ui-slider-track.ui-mini {
	margin: 0 15px 0 68px;

See screen shot. 
image

**Comment by arschmitz** [comment]
@ldeluca its not in your screen shot as its mini only its also very hard to see but if you flip back and forth between http://demos.jquerymobile.com/1.4.0/rangeslider/ and yours you will see the margins on the rangeslider shifting.

**Comment by ldeluca** [comment]
@arschmitz okay, i see what you're referring to: 
image

when I throw another window over to align i see:
image

that offset is what people are referring to as "broken" correct?

**Comment by arschmitz** [comment]
Correct you can also see the first input should line up with the R in range slider and its a little inset. And yes this is the "broken" bit.

**Comment by ldeluca** [comment]
@arschmitz what's even stranger is chrome dev tools says my css isn't even being applied....

image

**Comment by jaspermdegroot** [comment]
I suggest we close this PR, revert the commit that caused the regression (https://github.com/jquery/jquery-mobile/commit/ab067cb8147f1b1155db0622fda18b792122b730), re-open https://github.com/jquery/jquery-mobile/issues/6795 and close https://github.com/jquery/jquery-mobile/issues/7821 as fixed.

Issue https://github.com/jquery/jquery-mobile/issues/7821 is not the only regression from that commit. See for example the "buttons in grids demo" (http://demos.jquerymobile.com/1.4.5/grids-buttons/#Minisized).

```ui-mini``` can be added to almost all components. There is no reason that components should get margin at any side, while they don't get that when fullsize.

I will comment on https://github.com/jquery/jquery-mobile/issues/6795 because the issue had actually nothing to do with mini size. It also happens with fullsize buttons.

**Comment by jaspermdegroot** [comment]
Closing this PR in favor of PR #7999. Thanks!

**Pull request closed without merging**
