### PR TITLE
Component:  Update Build info in README #8339

### PR DESCRIPTION
**Pull request by marti1125**
Its a PR for check the progress of README.md

### CODE REVIEW

**Comment by jaspermdegroot** [comment]
@marti1125 - Thanks for the PR! We have to look into why some tests are failing.

**Comment by jaspermdegroot** [comment]
@arschmitz - Can you look at the failing test and say if these are caused by table and not by the changes in this PR? Thanks!

cc. @marti1125

**Comment by arschmitz** [comment]
@jaspermdegroot this looks good those are expected failures until the table classes pr lands

**Comment by arschmitz** [comment]
:+1:

**Comment by jaspermdegroot** [comment]
Landed. Thanks @marti1125 !

**Pull request closed without merging**
