### PR TITLE
Select: hide generated <span> from AT

### LINKED ISSUE #8256: Select menu - "faked" current selection text separately announced by screen readers
Taking the first example from http://demos.jquerymobile.com/1.4.5/selectmenu/, based on the following simplified markup

```
<div ... class="...">
  <span>The 1st Option</span>
  <select name="..." ...>
    <option value="1">The 1st Option</option>
    ...
  </select>
</div>
```

when using TalkBack/Android or VoiceOver/iOS, the `<span>` is read/announced separately, before the actual `<select>`. This results in redundant/inappropriate output (as the `<span>` is not announced as being actionable, and the current option is already announced once the user moves their screenreader focus to the actual `<select>`).

Solution would be to apply an `aria-hidden="true"` to that `<span>`

```
<div ... class="...">
  <span aria-hidden="true">The 1st Option</span>
  <select name="..." ...>
    <option value="1">The 1st Option</option>
    ...
  </select>
</div>
```

which suppresses that element completely from being seen/announced by SRs

### PR DESCRIPTION
**Pull request by patrickhlauke**
Closes #8256

### CODE REVIEW

**Comment by arschmitz** [comment]
@patrickhlauke thank you looks good ill land this shortly

**Comment by patrickhlauke** [comment]
wasn't able to install the toolchain for building/testing on my win machine locally at this stage, so hope this tiny tweak doesn't have any side effects i didn't foresee. fingers crossed ;)

**Comment by arschmitz** [comment]
@patrickhlauke travis will let us know soon enough

**Comment by patrickhlauke** [comment]
those travis errors seem unrelated to my actual PR...

**Comment by arschmitz** [comment]
@patrickhlauke yeah we have been having trouble with those randomly failing lately need to track that down

**Comment by patrickhlauke** [comment]
do i need to try and force a retest of Travis (and if so, is there a magic incantation to do so from here)?

**Comment by arschmitz** [comment]
@patrickhlauke nope your good

**Pull request closed without merging**
