### PR TITLE
All: Update boilerplate

### PR DESCRIPTION
**Pull request by gabrielschulhof**
Fixes gh-7973

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
See also https://github.com/jquery/api.jquerymobile.com/issues/367 for reasons why some docs/demos metadata comments are missing.

**Comment by gabrielschulhof** [comment]
Please add missing docs/demos to https://github.com/jquery/api.jquerymobile.com/issues/367!

**Comment by arschmitz** [comment]
:+1:

**Comment by gabrielschulhof** [comment]
Pushed this to 1.5-dev.

**Pull request closed without merging**
