### PR TITLE
Flipswitch: Fix text color

### PR DESCRIPTION
**Pull request by arschmitz**
Fixes gh-7701

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@jaspermdegroot Could you please weigh in on this before we add another ```!important```?

**Comment by gabrielschulhof** [comment]
:+1:

**Comment by gabrielschulhof** [comment]
@jaspermdegroot nm, saw your comment in the issue.

**Comment by jaspermdegroot** [comment]
Text shadow is changing as well on hover so we have to change it to:
```
.ui-flipswitch-active .ui-btn { color: inherit !important; text-shadow: inherit !important; }
```

**Pull request closed without merging**
